# Generated by Django 4.2.3 on 2023-07-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
